version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CONNECTION_URL=mongodb://mongodb:27017/todolist
      - PORT=5000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DEFAULT_CLIENT_URL=${DEFAULT_CLIENT_URL}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 